spring:
  application:
    name: consulServer1
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: service-producer
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8113