spring:
  application:
    name: consulClient
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
  zipkin:
    base-url: http://localhost:9411
    service:
      name: consulClient
server:
  port: 8111